### ISSUE TITLE
Skeleton hangs on installing packages

### ISSUE THREAD

**Issue by sircharleswatson** [alaister/brunch-with-elm#2]
When I run `brunch new --skeleton alaister/brunch-with-elm` it creates the skeleton directory layout but then when it gets to "Installing packages..." it just hangs there not doing anything.

```
19 Aug 09:29:08 - log: Pulling recent changes from git repo "git://github.com/alaister/brunch-with-elm.git" to "/Users/Charles/.brunch/skeletons/dbf43236df1c522d905c751011542eb0820047a3"...
19 Aug 09:29:09 - log: Pulled master into "/Users/Charles/.brunch/skeletons/dbf43236df1c522d905c751011542eb0820047a3"
19 Aug 09:29:09 - log: Created skeleton directory layout
19 Aug 09:29:09 - log: Installing packages...
```

If I cancel and run `elm package install` myself, it processes and then I can start the app just fine.

I'm not sure if this is an issue with the skeleton or with brunch, but I thought I'd try here first.

**Comment by alaister** [comment]
Hey @sircharleswatson,
You are correct. I tried and realised I was getting the same issue as you. I have now fixed the problem.
When npm ran `elm package install` it required the user to press `y` to confirm they want the packages to be installed. I have added a `-y` to the end of the `postinstall` script so it now does not require the user to do anything.

Please reattempt running `brunch new --skeleton alaister/brunch-with-elm` and let me know if it works for you 😃

**Comment by arunmascarenhas** [comment]
@alaister 
Thanks for fixing that. I am new to brunch and am still figuring it out.
